# PREPROCESSING

In [1]:
# Importar os módulos

import numpy as np
import pandas as pd
import random as rd

# DATASET EXEMPLO I

In [2]:
# Definir o tamanho e a semente
tamanho = 20
rd.seed = 42

# Criar as variáveis aleatórias
sx = [rd.sample(['F', 'M'], 1)[0] for _ in range(tamanho)]
idade = [rd.sample(list(range(18, 75)), 1)[0] for _ in range(tamanho)]
classe = [rd.sample(['A', 'B', 'C'], 1)[0] for _ in range(tamanho)]

# Criar um dicionário
dic = {'sexo': sx, 'idade': idade, 'classe': classe}

# Criar o dataset
dados = pd.DataFrame(dic)
dados.sample(5)

sexo  idade classe
1     M     24      B
3     M     61      B
13    M     45      C
14    M     72      C
7     F     32      A

# * LABELENCODER

In [3]:
# Importar o módulo

from sklearn.preprocessing import LabelEncoder

In [4]:
# Criar o objeto

tf = LabelEncoder()
# Treinando o processador
tf.fit(dados[['classe']])

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LabelEncoder()

In [5]:
# Fazer a transformação

resultado = tf.fit_transform(dados[['classe']])
resultado

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 1, 2, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 2, 2, 2, 2, 1, 2, 0])

In [6]:
# Inverter a transformação

tf.inverse_transform(resultado)

array(['B', 'B', 'C', 'B', 'B', 'B', 'A', 'A', 'A', 'A', 'B', 'B', 'A',
       'C', 'C', 'C', 'C', 'B', 'C', 'A'], dtype=object)

# * ONEHOTENCODER

In [7]:
# Importar o módulo

from sklearn.preprocessing import OneHotEncoder

In [8]:
# Criar o objeto
tf = OneHotEncoder()

# Treinar o processador
tf.fit(dados[['classe']])

OneHotEncoder()

In [9]:
# Fazer a transformação

resultado = tf.fit_transform(dados[['classe']]).toarray()
resultado

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [10]:
# Inverter a transformação

tf.inverse_transform(resultado)

array([['B'],
       ['B'],
       ['C'],
       ['B'],
       ['B'],
       ['B'],
       ['A'],
       ['A'],
       ['A'],
       ['A'],
       ['B'],
       ['B'],
       ['A'],
       ['C'],
       ['C'],
       ['C'],
       ['C'],
       ['B'],
       ['C'],
       ['A']], dtype=object)

# * MINMAXSCALER

In [11]:
# Importar o módulo

from sklearn.preprocessing import MinMaxScaler

In [12]:
# Criar o objeto

tf = MinMaxScaler()

# Treinar o processador
tf.fit(dados[['idade']])

MinMaxScaler()

In [13]:
# Fazer a transformação

resultado = tf.fit_transform(dados[['idade']])
resultado

array([[0.26923077],
       [0.07692308],
       [0.76923077],
       [0.78846154],
       [0.67307692],
       [0.92307692],
       [0.51923077],
       [0.23076923],
       [0.        ],
       [0.53846154],
       [0.17307692],
       [0.36538462],
       [0.30769231],
       [0.48076923],
       [1.        ],
       [0.98076923],
       [0.84615385],
       [1.        ],
       [0.48076923],
       [0.21153846]])

In [14]:
# Inverter a transformação

tf.inverse_transform(resultado)

array([[34.],
       [24.],
       [60.],
       [61.],
       [55.],
       [68.],
       [47.],
       [32.],
       [20.],
       [48.],
       [29.],
       [39.],
       [36.],
       [45.],
       [72.],
       [71.],
       [64.],
       [72.],
       [45.],
       [31.]])

# * STANDARDSCALER

In [15]:
# Importar o módulo

from sklearn.preprocessing import StandardScaler

In [16]:
# Criar o objeto

tf = StandardScaler()

# Treinar o processador
tf.fit(dados[['idade']])

StandardScaler()

In [17]:
# Fazer a transformação

resultado = tf.fit_transform(dados[['idade']])
resultado

array([[-0.83051647],
       [-1.43895345],
       [ 0.75141967],
       [ 0.81226337],
       [ 0.44720118],
       [ 1.23816925],
       [-0.0395484 ],
       [-0.95220387],
       [-1.68232824],
       [ 0.02129529],
       [-1.13473496],
       [-0.52629799],
       [-0.70882908],
       [-0.1612358 ],
       [ 1.48154404],
       [ 1.42070034],
       [ 0.99479446],
       [ 1.48154404],
       [-0.1612358 ],
       [-1.01304757]])

In [18]:
# Inverter a transformação

tf.inverse_transform(resultado)

array([[34.],
       [24.],
       [60.],
       [61.],
       [55.],
       [68.],
       [47.],
       [32.],
       [20.],
       [48.],
       [29.],
       [39.],
       [36.],
       [45.],
       [72.],
       [71.],
       [64.],
       [72.],
       [45.],
       [31.]])

# DATASET EXEMPLO II

In [19]:
# Criar um novo dataset

dados = pd.DataFrame({'cores':['Amarelo', 'Verde', 'vermelho'], 'formas': ['circulo', 'quadrado', 'triângulo']})
dados

cores     formas
0   Amarelo    circulo
1     Verde   quadrado
2  vermelho  triângulo

# * GET_DUMMIES

In [20]:
# Fazer o dummies

pd.get_dummies(dados)

cores_Amarelo  cores_Verde  ...  formas_quadrado  formas_triângulo
0              1            0  ...                0                 0
1              0            1  ...                1                 0
2              0            0  ...                0                 1

[3 rows x 6 columns]

# * ONEHOTENCODER

In [21]:
# Importar o módulo

from sklearn.preprocessing import OneHotEncoder

In [22]:
# Criar o objeto

tf = OneHotEncoder(handle_unknown='ignore', sparse=False)

# Treinar o processador
tf.fit(dados)

OneHotEncoder(handle_unknown='ignore', sparse=False)

In [23]:
# Verificar as categorias
tf.categories_

[array(['Amarelo', 'Verde', 'vermelho'], dtype=object),
 array(['circulo', 'quadrado', 'triângulo'], dtype=object)]

In [24]:
# Fazer a transformação

resultado = tf.fit_transform(dados)
resultado

array([[1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1.]])

In [25]:
# Verificar as colunas do dataset

tf.feature_names_in_

array(['cores', 'formas'], dtype=object)

In [26]:
# Verificar as colunas que foram criadas

tf.get_feature_names_out()

array(['cores_Amarelo', 'cores_Verde', 'cores_vermelho', 'formas_circulo',
       'formas_quadrado', 'formas_triângulo'], dtype=object)

In [27]:
# Criar dataset com as colunas nomeadas
dadosnew = pd.DataFrame(resultado, columns=tf.get_feature_names_out())
dadosnew

cores_Amarelo  cores_Verde  ...  formas_quadrado  formas_triângulo
0            1.0          0.0  ...              0.0               0.0
1            0.0          1.0  ...              1.0               0.0
2            0.0          0.0  ...              0.0               1.0

[3 rows x 6 columns]

In [28]:
# Inverter a transformação

tf.inverse_transform(dadosnew)

array([['Amarelo', 'circulo'],
       ['Verde', 'quadrado'],
       ['vermelho', 'triângulo']], dtype=object)

# * ORDINALENCODER

In [29]:
# Importar o módulo

from sklearn.preprocessing import OrdinalEncoder

In [30]:
# Criar o objeto

tf = OrdinalEncoder()

# Treinar o processador
tf.fit(dados)

OrdinalEncoder()

In [31]:
# Verificar as categorias

tf.categories_

[array(['Amarelo', 'Verde', 'vermelho'], dtype=object),
 array(['circulo', 'quadrado', 'triângulo'], dtype=object)]

In [32]:
# Fazer a transformação

resultado = tf.fit_transform(dados)
resultado

array([[0., 0.],
       [1., 1.],
       [2., 2.]])

In [33]:
# Criar dataset transformado
 
dadosnew = pd.DataFrame(tf.fit_transform(dados), columns=dados.columns)
dadosnew

cores  formas
0    0.0     0.0
1    1.0     1.0
2    2.0     2.0

In [34]:
# Inverter a transformação
tf.inverse_transform(dadosnew)

array([['Amarelo', 'circulo'],
       ['Verde', 'quadrado'],
       ['vermelho', 'triângulo']], dtype=object)