# PREPROCESSING

In [1]:
# Importar os módulos

import numpy as np
import pandas as pd
import random as rd

In [2]:
# Versões dos módulos

!python --version
%reload_ext watermark
%watermark --iversions

Python 3.9.7
numpy : 1.20.3
pandas: 1.3.4



# DATASET EXEMPLO I

In [3]:
# Definir o tamanho e a semente
tamanho = 20
rd.seed = 42

# Criar as variáveis aleatórias
sx = [rd.sample(['F', 'M'], 1)[0] for _ in range(tamanho)]
idade = [rd.sample(list(range(18, 75)), 1)[0] for _ in range(tamanho)]
classe = [rd.sample(['A', 'B', 'C'], 1)[0] for _ in range(tamanho)]

# Criar um dicionário
dic = {'sexo': sx, 'idade': idade, 'classe': classe}

# Criar o dataset
dados = pd.DataFrame(dic)
dados.sample(5)

sexo  idade classe
9     M     66      B
17    F     50      A
4     M     35      A
19    F     40      B
8     F     40      A

# * LABELENCODER

In [4]:
# Importar o módulo

from sklearn.preprocessing import LabelEncoder

In [5]:
# Criar o objeto

tf = LabelEncoder()
# Treinando o processador
tf.fit(dados[['classe']])

C:\tools\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LabelEncoder()

In [6]:
# Fazer a transformação

resultado = tf.fit_transform(dados[['classe']])
resultado

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 2, 2, 0, 0, 1, 1, 0, 1, 1])

In [7]:
# Inverter a transformação

tf.inverse_transform(resultado)

array(['A', 'B', 'A', 'A', 'A', 'A', 'B', 'B', 'A', 'B', 'B', 'C', 'C',
       'A', 'A', 'B', 'B', 'A', 'B', 'B'], dtype=object)

# * ONEHOTENCODER

In [8]:
# Importar o módulo

from sklearn.preprocessing import OneHotEncoder

In [9]:
# Criar o objeto
tf = OneHotEncoder()

# Treinar o processador
tf.fit(dados[['classe']])

OneHotEncoder()

In [10]:
# Fazer a transformação

resultado = tf.fit_transform(dados[['classe']]).toarray()
resultado

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [11]:
# Inverter a transformação

tf.inverse_transform(resultado)

array([['A'],
       ['B'],
       ['A'],
       ['A'],
       ['A'],
       ['A'],
       ['B'],
       ['B'],
       ['A'],
       ['B'],
       ['B'],
       ['C'],
       ['C'],
       ['A'],
       ['A'],
       ['B'],
       ['B'],
       ['A'],
       ['B'],
       ['B']], dtype=object)

# * MINMAXSCALER

In [12]:
# Importar o módulo

from sklearn.preprocessing import MinMaxScaler

In [13]:
# Criar o objeto

tf = MinMaxScaler()

# Treinar o processador
tf.fit(dados[['idade']])

MinMaxScaler()

In [14]:
# Fazer a transformação

resultado = tf.fit_transform(dados[['idade']])
resultado

array([[0.25454545],
       [0.30909091],
       [0.72727273],
       [0.4       ],
       [0.29090909],
       [0.05454545],
       [0.41818182],
       [0.65454545],
       [0.38181818],
       [0.85454545],
       [0.94545455],
       [0.70909091],
       [0.92727273],
       [0.76363636],
       [0.        ],
       [0.2       ],
       [1.        ],
       [0.56363636],
       [0.49090909],
       [0.38181818]])

In [15]:
# Inverter a transformação

tf.inverse_transform(resultado)

array([[33.],
       [36.],
       [59.],
       [41.],
       [35.],
       [22.],
       [42.],
       [55.],
       [40.],
       [66.],
       [71.],
       [58.],
       [70.],
       [61.],
       [19.],
       [30.],
       [74.],
       [50.],
       [46.],
       [40.]])

# * STANDARDSCALER

In [16]:
# Importar o módulo

from sklearn.preprocessing import StandardScaler

In [17]:
# Criar o objeto

tf = StandardScaler()

# Treinar o processador
tf.fit(dados[['idade']])

StandardScaler()

In [18]:
# Fazer a transformação

resultado = tf.fit_transform(dados[['idade']])
resultado

array([[-0.90668308],
       [-0.71779077],
       [ 0.7303836 ],
       [-0.40297026],
       [-0.78075488],
       [-1.59928822],
       [-0.34000616],
       [ 0.47852718],
       [-0.46593436],
       [ 1.17113232],
       [ 1.48595283],
       [ 0.66741949],
       [ 1.42298873],
       [ 0.8563118 ],
       [-1.78818053],
       [-1.09557539],
       [ 1.67484514],
       [ 0.16370667],
       [-0.08814974],
       [-0.46593436]])

In [19]:
# Inverter a transformação

tf.inverse_transform(resultado)

array([[33.],
       [36.],
       [59.],
       [41.],
       [35.],
       [22.],
       [42.],
       [55.],
       [40.],
       [66.],
       [71.],
       [58.],
       [70.],
       [61.],
       [19.],
       [30.],
       [74.],
       [50.],
       [46.],
       [40.]])

# DATASET EXEMPLO II

In [20]:
# Criar um novo dataset

dados = pd.DataFrame({'cores':['Amarelo', 'Verde', 'vermelho'], 'formas': ['circulo', 'quadrado', 'triângulo']})
dados

cores     formas
0   Amarelo    circulo
1     Verde   quadrado
2  vermelho  triângulo

# * GET_DUMMIES

In [21]:
# Fazer o dummies

pd.get_dummies(dados)

cores_Amarelo  cores_Verde  cores_vermelho  formas_circulo  \
0              1            0               0               1   
1              0            1               0               0   
2              0            0               1               0   

   formas_quadrado  formas_triângulo  
0                0                 0  
1                1                 0  
2                0                 1

# * ONEHOTENCODER

In [22]:
# Importar o módulo

from sklearn.preprocessing import OneHotEncoder

In [23]:
# Criar o objeto

tf = OneHotEncoder(handle_unknown='ignore', sparse=False)

# Treinar o processador
tf.fit(dados)

OneHotEncoder(handle_unknown='ignore', sparse=False)

In [24]:
# Verificar as categorias
tf.categories_

[array(['Amarelo', 'Verde', 'vermelho'], dtype=object),
 array(['circulo', 'quadrado', 'triângulo'], dtype=object)]

In [25]:
# Fazer a transformação

resultado = tf.fit_transform(dados)
resultado

array([[1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1.]])

In [26]:
# Verificar as colunas do dataset

tf.feature_names_in_

AttributeError: 'OneHotEncoder' object has no attribute 'feature_names_in_'

In [ ]:
# Verificar as colunas que foram criadas

tf.get_feature_names_out()

In [ ]:
# Criar dataset com as colunas nomeadas
dadosnew = pd.DataFrame(resultado, columns=tf.get_feature_names_out())
dadosnew

In [ ]:
# Inverter a transformação

tf.inverse_transform(dadosnew)

# * ORDINALENCODER

In [ ]:
# Importar o módulo

from sklearn.preprocessing import OrdinalEncoder

In [ ]:
# Criar o objeto

tf = OrdinalEncoder()

# Treinar o processador
tf.fit(dados)

In [ ]:
# Verificar as categorias

tf.categories_

In [ ]:
# Fazer a transformação

resultado = tf.fit_transform(dados)
resultado

In [ ]:
# Criar dataset transformado
 
dadosnew = pd.DataFrame(tf.fit_transform(dados), columns=dados.columns)
dadosnew

In [ ]:
# Inverter a transformação
tf.inverse_transform(dadosnew)